spring:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    refresh-token: ${GOOGLE_REFRESH_TOKEN}
    from-email: ${GOOGLE_FROM_EMAIL}
    to-email: ${GOOGLE_TO_EMAIL}
server:
  servlet:
    context-path: /demo